
create table cart (id bigint generated by default as identity, amount decimal(19,2), discount decimal(19,2), customer_id bigint, primary key (id));
create table cart_cart_items (order_id bigint not null, cart_items_id bigint not null, cart_id bigint not null);
create table cart_item (id bigint generated by default as identity, price decimal(19,2), quantity integer, cart_id bigint, product_id bigint, primary key (id));
create table cart_item_side_products (cart_item_id bigint not null, side_products_id bigint not null);
create table customer (id bigint generated by default as identity, primary key (id));
create table product (id bigint generated by default as identity, price decimal(19,2) not null, product_name varchar(255) not null, cart_item_id bigint, primary key (id));
create table side_product (id bigint generated by default as identity, price decimal(19,2) not null, product_name varchar(255) not null, cart_item_id bigint, primary key (id));
alter table cart_cart_items add constraint UK_674a9j0b3m6nnmiaha89jhjm3 unique (cart_items_id);
alter table cart add constraint FKdebwvad6pp1ekiqy5jtixqbaj foreign key (customer_id) references customer;
alter table cart_cart_items add constraint FKfsg34uqhcn23ta9b4soqhc3gc foreign key (cart_items_id) references cart_item;
alter table cart_cart_items add constraint FK3d3pfn2ms2cxj16y1lk66npge foreign key (order_id) references cart;
alter table cart_cart_items add constraint FKn4wj4t2u48qwhsp9dhugejs8u foreign key (cart_id) references cart;
alter table cart_item add constraint FK1uobyhgl1wvgt1jpccia8xxs3 foreign key (cart_id) references cart;
alter table cart_item add constraint FKjcyd5wv4igqnw413rgxbfu4nv foreign key (product_id) references product;
alter table cart_item_side_products add constraint FKh1q6asl09gnuvj0j3r5ayo7f2 foreign key (side_products_id) references side_product;
alter table cart_item_side_products add constraint FKf2nf9pcrhcbcn3nwnhgr67cgl foreign key (cart_item_id) references cart_item;
alter table product add constraint FK63g9e5ap67bgf4wi2r5caq4yd foreign key (cart_item_id) references cart_item;
alter table side_product add constraint FK1e88cmvs6e32c59wakn66htxp foreign key (cart_item_id) references cart_item;

INSERT INTO product VALUES
(1, 4.00, 'Black Coffee', NULL),
(2, 4.00, 'Latte', NULL),
(3, 6.00, 'Mocha', NULL),
(4, 3.00, 'Tea', NULL);

INSERT INTO side_product VALUES
(1, 2.00, 'Milk', NULL),
(2, 3.00, 'Hazelnut syrup', NULL),
(3, 5.00, 'Chocolate sauce', NULL),
(4, 2.00, 'Lemon', NULL);
