CREATE TABLE CART(
    ID BIGINT NOT NULL,
    AMOUNT DECIMAL(19, 2),
    DISCOUNT DECIMAL(19, 2)
);
ALTER TABLE CART ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY("ID");

CREATE TABLE CART_CART_ITEMS(
    ORDER_ID BIGINT NOT NULL,
    CART_ITEMS_ID BIGINT NOT NULL,
    CART_ID BIGINT NOT NULL
);

CREATE TABLE CART_ITEM(
    ID BIGINT NOT NULL,
    PRICE DECIMAL(19, 2),
    QUANTITY INTEGER,
    PRODUCT_ID BIGINT NOT NULL
);
ALTER TABLE CART_ITEM ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY("ID");

CREATE TABLE CART_ITEM_SIDE_PRODUCTS(
    CART_ITEM_ID BIGINT NOT NULL,
    SIDE_PRODUCTS_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART_ITEM_SIDE_PRODUCTS;
CREATE TABLE CUSTOMER(
    ID BIGINT NOT NULL,
    CART_ID BIGINT NOT NULL
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY("ID");

CREATE TABLE CUSTOMER_ORDERS(
    CUSTOMER_ID BIGINT NOT NULL,
    ORDERS_ID BIGINT NOT NULL
);

CREATE TABLE PRODUCT(
    ID BIGINT NOT NULL,
    PRICE DECIMAL(19, 2),
    PRODUCT_NAME VARCHAR(255),
    CART_ITEM_ID BIGINT NULL
);
ALTER TABLE PRODUCT ADD CONSTRAINT CONSTRAINT_18 PRIMARY KEY("ID");

CREATE TABLE SIDE_PRODUCT(
    ID BIGINT NOT NULL,
    PRICE DECIMAL(19, 2),
    PRODUCT_NAME VARCHAR(255),
    CART_ITEM_ID BIGINT NULL
);
ALTER TABLE SIDE_PRODUCT ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY("ID");

INSERT INTO PRODUCT VALUES
(1, 4.00, 'Black Coffee', NULL),
(2, 4.00, 'Latte', NULL),
(3, 6.00, 'Mocha', NULL),
(4, 3.00, 'Tea', NULL);

INSERT INTO SIDE_PRODUCT VALUES
(1, 2.00, 'Milk', NULL),
(2, 3.00, 'Hazelnut syrup', NULL),
(3, 5.00, 'Chocolate sauce', NULL),
(4, 2.00, 'Lemon', NULL);
